apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: grafana-pv
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi